USE sakila;

CREATE VIEW resume_1 AS
SELECT CUSTOMER.CUSTOMER_ID,  CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME, CUSTOMER.EMAIL, COUNT(RENTAL.RENTAL_ID) AS RENTAL_COUNT
FROM CUSTOMER
JOIN  RENTAL
ON CUSTOMER.CUSTOMER_ID = RENTAL.CUSTOMER_ID
GROUP BY CUSTOMER.CUSTOMER_ID;

CREATE TEMPORARY TABLE resumen_pagos_totales AS
SELECT resume_1.CUSTOMER_ID,  resume_1.FIRST_NAME, resume_1.LAST_NAME, resume_1.EMAIL, resume_1.RENTAL_COUNT, SUM(PAYMENT.AMOUNT) AS TOTAL_PAID
FROM resume_1
JOIN  PAYMENT
ON resume_1.CUSTOMER_ID = PAYMENT.CUSTOMER_ID
GROUP BY resume_1.CUSTOMER_ID;
 
WITH resumen_final AS (
	SELECT resume_1.CUSTOMER_ID, resume_1.FIRST_NAME, resume_1.LAST_NAME, resume_1.EMAIL , resume_1.RENTAL_COUNT, resumen_pagos_totales.TOTAL_PAID, ROUND((resumen_pagos_totales.TOTAL_PAID / resume_1.RENTAL_COUNT), 2) AS Average_payment_per_rental
	FROM resume_1
	JOIN  resumen_pagos_totales
	ON resume_1.CUSTOMER_ID = resumen_pagos_totales.CUSTOMER_ID
)
SELECT *
FROM resumen_final;
